### ISSUE TITLE
Troubleshooting remote access to Papercut web UI

### ISSUE THREAD

**Issue by drmcclelland** [ChangemakerStudios/Papercut-SMTP#187]
I've installed Papercut previously on Windows Server 2012, and had no issues accessing the web UI using this URL:   `http://<servername>:37408`

But now I've installed Papercut on a new server running Windows Server 2019, and I cannot access the web UI except from the server itself (http://127.0.0.1:37408).

I can telnet to the server on port 25, and I get the following message:  `220 Papercut.Service v6.5.0.0 ESMTP ready`

I cannot telnet to the server on port 37408, I get the following error:  `Could not open connection to the host, on port 37408: Connect failed`

I have checked, and Windows Firewall is OFF, so I don't think port blocking is the issue.  Does anyone have any other ideas how I can troubleshoot this?

**Comment by drmcclelland** [comment]
In order to troubleshoot this, I uninstalled the current release (v5.7.0) and installed the version I had previously used (v5.1.76) and now it's running fine on Windows Server 2019.   

Maybe there's an incompatibility that's been introduced along the way?

**Comment by TrippyZ** [comment]
Is it listening?  Try "netstat -an" and filter for that port no.

**Comment by Pesche401** [comment]
I have exactly the same problem on server 2019 and Release v5.7.0.0.
As i can use the website localy i see also the port ist listening when i use netstat.

Firewall cannot be the problem. I switcht it of for testing.
I also changed the config to accept another URL then 127.0.0.1.
It wokrs local but not from an other machine.

Is there a possiblity to configure these to allow access to the website from other machines?

**Comment by Jaben** [comment]
Have you tried setting the ```"HttpBaseAddress": "http://127.0.0.1"``` in the Papercut.Service.Settings.json to ```"HttpBaseAddress": "Any" ```?

**Comment by phanos** [comment]
I am seeing the same issue. I edited Papercut.Service.Settings.json and switched to "http://0.0.0.0", after restarting service, opened config file to find it reverted back to "http://127.0.0.1"

ProductVersion:   5.8.0+Branch.master.Sha.b51880d24f26884966df6542ffb5903c17ecec94

**Comment by phanos** [comment]
> I am seeing the same issue. I edited Papercut.Service.Settings.json and switched to "http://0.0.0.0", after restarting service, opened config file to find it reverted back to "http://127.0.0.1"
> 
> ProductVersion: 5.8.0+Branch.master.Sha.b51880d24f26884966df6542ffb5903c17ecec94

Ok, I figured out I needed to **stop** the service before making changes to the config, rather than restarting it after making a change.

I am now seeing this error message in the logs:

2021-09-08 14:33:52.072 -07:00 [ERR] [WebUI] Can not start Web UI Http server at "http://0.0.0.0:37408/"
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.HttpListenerException: The request is not supported
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(HttpListener listener, Func`2 appFunc, IList`1 addresses, IDictionary`2 capabilities, Func`2 loggerFactory)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(Func`2 app, IDictionary`2 properties)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(IAppBuilder builder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
   at Papercut.App.WebApi.PapercutWebServer.StartHttpServer() in C:\projects\papercut\src\Papercut.App.WebApi\WebServer.cs:line 107

**Comment by Plasmadog** [comment]
I had this issue as well. I've been using v5.51 successfully for ages, but v6 is unusable for the same use case.

**Comment by Jaben** [comment]
> 

Please use the following command or run the service with elevated (admin) permissions:

netsh http add urlacl url=http://+:37408/ user="NETWORK SERVICE"

**Comment by Jaben** [comment]
Please try latest and reopen this issue if the problem persists.
