### ISSUE TITLE
Error when running Papercust.Service.exe 5.8.0

### ISSUE THREAD

**Issue by qch1866** [ChangemakerStudios/Papercut-SMTP#194]
The following error can be seen when running 5.8.0 Papercust.Service.exe from command.
No such error when running 5.7.0

[10:17:09 INF] Configuration Result:
[Success] Name PapercutServerService
[Success] DisplayName Papercut SMTP Service
[Success] Description Papercut SMTP Backend Service
[Success] ServiceName PapercutServerService
[10:17:09 INF] Topshelf v4.3.0.0, .NET Framework 4.8.4400.0 (4.0.30319.42000)
[10:17:09 INF] The PapercutServerService service is now running, press Control+C to exit.
[10:17:09 INF] Publishing {"AppMeta": {"AppName": "Papercut.Service", "AppVersion": "5.8.0", "$type": "ApplicationMeta"}, "$type": "PapercutServicePreStartEvent"} to the Papercut Client
[10:17:09 INF] IPComm Server Ready: Listening for New Connections at 127.0.0.1:37403
[10:17:09 INF] Publishing {"AppMeta": {"AppName": "Papercut.Service", "AppVersion": "5.8.0", "$type": "ApplicationMeta"}, "$type": "PapercutServiceReadyEvent"} to the Papercut Client
[10:17:10 ERR] Unobserved Task Exception
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
[10:17:10 INF] [WebUI] Papercut Web UI is browsable at http://127.0.0.1:37408/
[10:17:11 INF] Starting Smtp Server on 0.0.0.0:25...

1. Go to C:\PapercustService.5.8.0
2. Run Papercut.Service.exe from command

 - OS: Windows 10

[Papercut.Service.log](https://github.com/ChangemakerStudios/Papercut-SMTP/files/7078029/Papercut.Service.log)

**Comment by Jaben** [comment]
This issue is fixed in the latest commit/version. Will release here very soon.
