### ISSUE TITLE
Emails not forwarded on enabled rule

### ISSUE THREAD

**Issue by ipa89** [ChangemakerStudios/Papercut-SMTP#222]
**Describe the bug**
There is a saved rule and enabled to forward email. It does not forward email. All emails can be seen in GUI, none of them is automatically forwarded. If I use GUI and click forward, the email is forwarded as expected, just auto-forward does not work. I also see this in a log:

```
022-04-04 16:43:20.634 -07:00 [INF] Starting Smtp Server on 0.0.0.0:25...
2022-04-04 16:43:28.735 -07:00 [INF] Publishing Event Received {"AppMeta":{"AppName":"Papercut.Service","AppVersion":"6.2.0","$type":"ApplicationMeta"},"$type":"PapercutServicePreStartEvent"} from Remote
2022-04-04 16:43:28.736 -07:00 [INF] Papercut Backend Service is running. SMTP disabled in UI.
2022-04-04 16:43:28.736 -07:00 [INF] Stopping Smtp Server
2022-04-04 16:43:28.736 -07:00 [INF] New SMTP connection from 0.0.0.0
2022-04-04 16:43:28.736 -07:00 [INF] Completed SMTP connection from 0.0.0.0
2022-04-04 16:43:28.736 -07:00 [ERR] Smtp Server Error
System.NullReferenceException: Object reference not set to an instance of an object.
   at SmtpServer.SmtpSessionManager.<RunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SmtpServer.SmtpServer.<StartAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Papercut.Infrastructure.Smtp.PapercutSmtpServer.<<StartAsync>b__14_0>d.MoveNext() in C:\projects\papercut-smtp\src\Papercut.Infrastructure.Smtp\PapercutSmtpServer.cs:line 125
2022-04-04 16:43:28.752 -07:00 [INF] Publishing Event Received {"AppMeta":{"AppName":"Papercut.Service","AppVersion":"6.2.0","$type":"ApplicationMeta"},"$type":"PapercutServiceReadyEvent"} from Remote
2022-04-04 16:43:28.768 -07:00 [WRN] Unobserved Task Exception
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
```

**To Reproduce**
1. Setup rules
2. Save rules
3. Restart service

**Expected behavior**
Email will be automatically forwarded when recived

**Screenshots**

**Desktop (please complete the following information):**
- Windows Server 2019, PapercutSMTP 6.2.0, this is a dev server

**Additional context**

**Comment by Jaben** [comment]
Would need to see the "RULE" you are using. Otherwise, this isn't very helpful.
